spring.application.name=hocjava
spring.datasource.url=jdbc:mariadb://localhost:3306/hocjava_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
server.servlet.context-path=/

# Bắt buộc encoding UTF-8 cho tất cả response
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.force-response=true

# Riêng cho static resources
spring.mvc.static-path-pattern=/**
spring.web.resources.chain.strategy.content.enabled=true

# Hiển thị lỗi trên trang lỗi
spring.web.error.include-message=never
spring.web.error.include-binding-errors=always